---
title: "Nest info"
format:
  html:
    include-after-body:
      text: |
        <script src="scripts/accordion.js"></script>
        <script src="scripts/nest_view_toggle.js"></script>
---

<!-- Setup -->

```{r setup}
#| include: false

library(glue)
library(leaflet)
library(sf)
library(tidyverse)

source(
  here::here("scripts/functions.R")
)

# custom functions --------------------------------------------------------

# Helper function for a nest accordian:

make_nest_accordion <-
  function(.x) {
    glue_data(
      .x,
"
<button class='accordion'><strong>{nest_id}.</strong> Species : {species}
</button>
<div class='panel'>
<ul>
<li><strong>Patch</strong>: {patch_id}</li>
<li><strong>Plant species</strong>: {substrate}</li>
<li><strong>Height</strong>: {height}</li>
<li><strong>Location description</strong>: {location_description}</li>
<li><strong>Discovered on</strong>: {discovery_date}</li>
<li><strong>Last checked on</strong>: {last_check}</li>
<li><strong>Current status</strong>: {last_status}</li>
</ul>
</div>
"
    )
  }
```

<!-- Nest data -->

```{r nest_data}
#| include: false

# nest data ---------------------------------------------------------------

nests_start <-
  here::here("data/field_data.rds") %>% 
  read_rds() %>% 
  pluck("nests") %>% 
  filter(nest_id != "N031") %>% 
  unnest(interval_data) %>% 
  summarize(
    last_check = last(date), 
    last_status = last(nest_status),
    .by = 
      c(
        nest_id:patch_id, 
        height,
        substrate, 
        location_description,
        discovery_date
      )
  ) %>% 
  mutate(
    across(
      where(is.character),
      ~ replace_na(.x, "Unknown")
    )
  ) 

nest_list <-
  nests_start %>% 
  split(.$nest_id) %>% 
  
  # I figured you would want to see it in the order of most recent to earliest:
  
  rev()

patch_list <-
  nests_start %>% 
  split(.$patch_id)
```

<!-- Spatial data: I haven't added any spatial features yet, but it's for the 
future ... -->

```{r spatial_data}
#| include: false
#| eval: false

# spatial data ---------------------------------------------------------------

list.files(
  here::here("data/spatial"),
  pattern = "geojson",
  full.names = TRUE
) %>%
  set_names_from_path() %>%
  set_names(
    names(.) %>% 
      str_remove("_locations") %>% 
      str_replace("(?<!s)$", "s")
  ) %>% 
  map(
    ~ st_read(.x, quiet = TRUE) %>%
      st_transform(4326) %>% 
      
      # Add icon ids:
      
      mutate(
        icon_id = 
          case_when(
            str_detect(name, "cb|cam") ~ 
              str_extract(name, "(cb|cam)_[0-6]$"),
            str_detect(name, "^N") ~ "nest",
            str_detect(name, "^point") ~ "pc",
            .default = "patch"
          ),
        .after = name
      )
  ) %>% 
  list2env(.GlobalEnv)

# Icons:

icons <-
  list.files(
    here::here("icons/map_icons"), 
    pattern = "png$",
    full.names = TRUE
  ) %>% 
  set_names_from_path() %>% 
  map(
    ~ makeIcon(
      iconUrl = base64enc::dataURI(file = .x, mime = "image/png"),
      iconWidth = 26,
      iconHeight = 26,
      iconAnchorX = 13,
      iconAnchorY = 26
    )
  ) %>% 
  do.call(iconList, .)

# nest status -------------------------------------------------------------

# Read and process nest data for map:

nests_coded <- 
  read_rds(
    here::here("data/field_data.rds")
  ) %>% 
  pluck("nests") %>% 
  unnest(interval_data) %>% 
  mutate(
    nest_id, 
    patch_id, 
    nest_fate, 
    date = as_date(date),
    across(
      host_eggs:host_young,
      ~ as.numeric(.x)
    ),
    .keep = "none"
  ) %>% 
  slice_max(date, by = nest_id) %>% 
  mutate(
    name = nest_id,
    icon_id = 
      case_when(
        nest_fate %in% c("Success", "Failure") ~ "nest_old",
        host_eggs == 0 & 
          host_young == 0 ~  "nest_building",
        is.na(host_eggs) & is.na(host_young) ~ "nest_unknown",
        .default = "nest_active"
      ),
    .keep = "none"
  ) %>% 
  left_join(
    select(nests, !icon_id),
    .,
    by = "name"
  ) %>% 
  filter(name != "N031")

# Simplify path lines

paths <-
  tracks %>% 
  rmapshaper::ms_simplify(keep = 0.20)

```

<!-- Mapping: This is also not implemented yet -->

```{r mapping, eval = FALSE}

map <-
  leaflet() %>%
  
  # Base tile layers:
  
  addProviderTiles(
    providers$Esri.WorldImagery,
    group = "Satellite",
    options = tileOptions(maxZoom = 21)
  ) %>%
  addProviderTiles(
    providers$OpenStreetMap,
    group = "Street Map"
  ) %>%
  
  # Patches drawn first so point layers render on top:
  
  addPolygons(
    data = patches,
    fillColor = "#ffffff",
    fillOpacity = 0.2,
    color = "#0000ff",
    weight = 1.5,
    opacity = 0.5,
    popup = ~ name,
    label = ~ name,
    group = "Patches"
  ) %>%
  
  addPolylines(
    data = paths,
    weight = 3,
    opacity = 0.7,
    dashArray = "2, 5",
    color = "#ffff00"
  ) %>% 
  
  # Nests
  
  addMarkers(
    data = nests,
    icon = ~ icons[icon_id],
    popup = ~ name,
    label = ~ name,
    group = "Nests"
  ) 
```


<div class="nest-view-toggle">
  <button class="nest-view-button active" data-view="all">All nests</button>
  <button class="nest-view-button" data-view="patch">By patch</button>
</div>

<!-- Accordion by nest: This is implemented! -->

<div id="nest-view-all" class = "nest-view">
  <div class="accordion-group">

```{r all-nest-accordion}
#| output: asis

nest_list %>% 
  walk(
    ~ make_nest_accordion(.x) %>% 
      cat()
  )
```

  </div>
</div>

<!-- Accordion by patch: This is also implemented! -->

<div id="nest-view-patch" class="nest-view" style="display: none;">
  <div class="accordion-group patch-accordion-group">

```{r by-patch-accordion}
#| output: asis

patch_list %>% 
  iwalk(
    ~ {
      patch_name <- .y
      patch_nests <- .x
      
      # Outer accordion:

      cat(
        glue(
          "
          <button class='accordion patch-accordion'>
            <strong>Patch: {patch_name}</strong> ({nrow(patch_nests)} nests)
          </button>
          <div class='panel patch-panel'>
            <div class='accordion-group nest-accordion-group'>
          "
        )
      )
      
      # Inner accordion

      patch_nests %>% 
        split(.$nest_id) %>% 
        rev() %>% 
        walk(
          ~ make_nest_accordion(.x) %>% 
            cat()
        )
      cat("</div></div>")
    }
  )
```

  </div>
</div>


