---
format:
  pdf:
    documentclass: article
    fontsize: 11pt
    geometry: margin=1in
    pdf-engine: xelatex
    mainfont: "Times New Roman"
    include-in-header:
      text: |
        \setlength{\parskip}{0pt}
        \setlength{\parindent}{0pt}
        \usepackage{titlesec}
        \titleformat{\subsection}[block]{\normalfont\large\bfseries}{}{0em}{}[\titlerule]
        \titlespacing*{\subsection}{0pt}{1.5em}{0.5em}
editor: source
editor_options: 
  chunk_output_type: console
execute:
  echo: false
  warning: false
  message: false
---

```{r}

library(kableExtra)
library(glue)
library(here)
library(tidyverse)

here("scripts/functions.R") %>% 
  source()

# get and process data ----------------------------------------------------

next_nest_checks <-
  here("data", "temp_nest_checking.rds") %>% 
  read_rds()

next_pred_cam_maintenance <-
  here("data", "predator_camera_maintenance.rds") %>% 
  read_rds() %>% 
  mutate(
    patch,
    date = next_maintenance,
    camera_id = 
      str_extract_all(camera_id, "[0-2]$"),
    .keep = "none"
  ) %>% 
    summarize(
      predator_cameras = 
        str_flatten(camera_id, collapse = ", "),
      .by = !camera_id
    )

schedule <- 
  here("data", "season_schedule.rds") %>% 
  read_rds() %>% 
  unnest(patch_counts) %>% 
  unnest(boards) %>% 
  filter(
    week ==
      week(today() + 1) - 18,
  ) %>% 
  summarize(
    boards = 
      str_flatten(board_id, collapse = ", "),
    .by = !board_id
  ) %>% 
  left_join(
    next_nest_checks,
    by = join_by(date == date, patch_count == patch)
  ) %>% 
  left_join(
    next_pred_cam_maintenance,
    by = join_by(date, patch_count == patch)
  ) %>% 
  mutate(
    departure_time = 
      (
        hm(arrive) - minutes(45)
      ) %>% 
      hms::hms() %>% 
      as.character() %>% 
      str_remove(":00$"),
    across(
      check_nests:predator_cameras,
      ~ replace_na(.x, "-")
    )
  )

schedule_list <-
  schedule %>% 
  split(schedule$day)

# list set-up -------------------------------------------------------------

day_names <- 
  c(
    Mon = "Monday",
    Tue = "Tuesday",
    Wed = "Wednesday",
    Thu = "Thursday",
    Fri = "Friday",
    Sat = "Saturday"
  )

days_ordered <- 
  intersect(
    names(day_names),
    names(schedule_list)
  )

day_data <- 
  days_ordered %>% 
  set_names() %>% 
  map(
    \(day) {
      day_data <- 
        schedule_list[[day]] %>% 
        select(
          date,
          arrive:helper
        ) %>% 
        distinct()
    }
  )

# custom functions --------------------------------------------------------

# Style for tabular output:

my_kable_style <-
  function(.kable) {
    .kable %>% 
      kable_styling(
        latex_options = 
          c(
            # "striped",
            "hold_position"
          ),
        full_width = FALSE,
        position = "left",
        font_size = 10
      )
  }

# Departure, arrival, and sunrise table:

morning_times <- 
  function(.day) {
    schedule_list %>% 
      pluck(.day) %>% 
      distinct(
        "Departure" = departure_time, 
        "Arrival" = arrive, 
        "Sunrise" = sunrise
      ) %>% 
      kable(
        align = 
          c("c", "c", "c")
      ) %>% 
      my_kable_style() %>% 
      column_spec(1:3, width = "14.5em")
  }

# Format point counts and coverboards for a given day:

pred_counts <- 
  function(.day) {
    schedule_list %>% 
      pluck(.day) %>% 
      mutate(
        Time = 
          str_c(date, sunrise) %>% 
          {
            ymd_hm(.) + 
              minutes(40 * (patch_order - 1))
          } %>% 
          format("%H:%M")
      ) %>% 
      select(
        Time,
        Patch = patch_count,
        Coverboards = boards,
        `Check nests` = check_nests,
        `Predator cameras` = predator_cameras
      ) %>% 
      kable(
        booktabs = TRUE,
        align =
          c(
            "c",
            "l",
            "c",
            "l"
          )
      ) %>% 
      my_kable_style() %>% 
      column_spec(1, width = "2.5em") %>% 
      column_spec(2, width = "7em") %>% 
      column_spec(3, width = "5em") %>% 
      column_spec(4, width = "14.5em") %>% 
      column_spec(5, width = "12em")
  }

# Helpers, pred_counts, and nests:

day_details <- 
  function(.wday) {
    wday_data <- 
      day_data %>% 
      pluck(.wday)
    
    str_c(
      "\n## ", day_names[.wday], " ",
      make_pretty_dates(wday_data$date), "\n\n",
      "*Helper: ", wday_data$helper, "*",
      "\\vspace{0em}",
      as.character(morning_times(.day = .wday)),
      "**Point count times, coverboards, and nests to check**:",
      "\\vspace{0em}",
      as.character(pred_counts(.day = .wday)),
      "\\vspace{0em}"
    ) %>% 
      str_flatten() %>%
      cat()
  }

# Nest searching order:

nest_searching_order <- 
  function(
    .day,
    .ordered = TRUE,
    .patches
  ) {
    
    if(.ordered) {
      searching_order <- 
        schedule_list %>% 
        pluck(.day) %>% 
        filter(patch_order != 1) %>%
        arrange(
          desc(patch_order)
        ) %>% 
        pull(patch_count) %>% 
        str_flatten(collapse = " \u2192 ")
    } else {
      searching_order <- 
        .patches %>% 
        str_flatten(collapse = " \u2192 ")
    }
    
    str_c(
      "**Nest searching**: ", searching_order
    ) %>% 
      str_flatten() %>%
      cat()
  }

# Nest searching activity details:

nest_searching <- 
  function(
    .day = "Tue",
    .ordered = TRUE,
    .helper,
    .patches,
    .helper_patch_1 = "-",
    .me_patch_1 = "-",
    .helper_patch_2 = "-",
    .me_patch_2 = "-"
  ) {
    
    if(.ordered) {
      start <- 
        schedule_list %>% 
        pluck(.day) %>% 
        filter(patch_order != 1) %>% 
        arrange(
          desc(patch_order)
        ) %>% 
        select(helper, patch_count) %>% 
        mutate(
          patch_count =
            factor(
              patch_count,
              levels = 
                patch_count
            )
        )
    } else {
      start <- 
        tibble(
          helper = .helper,
          patch_count = .patches
        ) %>% 
        mutate(
          patch_count =
            factor(
              patch_count,
              levels = 
                patch_count
            )
        )
    }
    
    crossing(
      Patch = start$patch_count,
      Person = 
        c(
          "TNS",
          pull(start, unique(helper))
        )
    ) %>% 
      mutate(
        Activities = 
          c(
            .helper_patch_1,
            .me_patch_1,
            .helper_patch_2,
            .me_patch_2
          )
      ) %>% 
      filter(
        Person != "-"
      ) %>% 
      kable() %>% 
      my_kable_style() %>%
      collapse_rows(
        columns = 1
      ) %>% 
      column_spec(1, width = "8em") %>% 
      column_spec(2, width = "5em") %>% 
      column_spec(3, width = "30.5em") %>% 
      as.character() %>% 
      str_flatten() %>% 
      cat()
  }

# Notes for additional details (outside of tables):

note <- 
  function(.note) {
    str_c(
      "*Note: ",
      .note,
      "*",
      "\n\n",
      "\\vspace{1em}"
    ) %>%
      str_flatten() %>%
      cat()
  }

```

# Weekly schedule: `r pretty_date_range(schedule)`

```{r results="asis"}

day_details(.wday = "Mon")

# Notes:

note("Let get nesty")

# Nest searching order:

nest_searching_order(
  .day = "Mon",
  
  # If schedule changes:
  
  # .ordered = FALSE,
  # .patches = c("", "")
)

# Nest searching activities:

nest_searching(
  .day = "Mon",
  .me_patch_1 = "-",
  .me_patch_2 = "-"
  
  # If schedule changes:
  
  # .ordered = FALSE,
  # .helper = "",
  # .patches = c("", "")
)

```

```{r results="asis"}

day_details(.wday = "Tue")

# Nest searching order:

nest_searching_order(
  .day = "Tue",
  
  # If schedule changes:
  
  # .ordered = FALSE,
  # .patches = c("", "")
)

# Nest searching activities:

nest_searching(
  .day = "Tue",
  .helper_patch_1 = "-",
  .me_patch_1 = "-",
  .helper_patch_2 = "-",
  .me_patch_2 = "-"
  
  # If schedule changes:
  
  # .ordered = FALSE,
  # .helper = "",
  # .patches = c("", "")
)

```

{{< pagebreak >}}

```{r results="asis"}

day_details(.wday = "Wed")

# Nest searching order:

nest_searching_order(
  .day = "Wed",
  
  # If schedule changes:
  
  # .ordered = FALSE,
  # .patches = c("", "")
)

# Nest searching activities:

nest_searching(
  .day = "Wed",
  .me_patch_1 = "-",
  .me_patch_2 = "-"
  
  # If schedule changes:
  
  # .ordered = FALSE,
  # .helper = "",
  # .patches = c("", ""),
  # .helper_patch_1 = "-",
  # .helper_patch_2 = "-"
)

```

```{r results="asis"}

day_details(.wday = "Thu")

# Nest searching order:

nest_searching_order(
  .day = "Tue",
  
  # If schedule changes:
  
  # .ordered = FALSE,
  # .patches = c("", "")
)

# Nest searching activities:

nest_searching(
  .day = "Tue",
  .helper_patch_1 = "-",
  .me_patch_1 = "-",
  .helper_patch_2 = "-",
  .me_patch_2 = "-"
  
  # If schedule changes:
  
  # .ordered = FALSE,
  # .helper = "",
  # .patches = c("", "")
)

```

{{< pagebreak >}}

```{r results="asis"}

day_details(.wday = "Fri")

# Nest searching order:

nest_searching_order(
  .day = "Fri",
  
  # If schedule changes:
  
  # .ordered = FALSE,
  # .patches = c("", "")
)

# Nest searching activities:

nest_searching(
  .day = "Fri",
  .me_patch_1 = "-",
  .me_patch_2 = "-"
  
  # If schedule changes:
  
  # .ordered = FALSE,
  # .helper = "",
  # .patches = c("", ""),
  # .helper_patch_1 = "-",
  # .helper_patch_2 = "-"
)

```

```{r results="asis"}

day_details(.wday = "Sat")

# Nest searching order:

nest_searching_order(
  .day = "Tue",
  
  # If schedule changes:
  
  # .ordered = FALSE,
  # .patches = c("", "")
)

# Nest searching activities:

nest_searching(
  .day = "Tue",
  .helper_patch_1 = "-",
  .me_patch_1 = "-",
  .helper_patch_2 = "-",
  .me_patch_2 = "-"
  
  # If schedule changes:
  
  # .ordered = FALSE,
  # .helper = "",
  # .patches = c("", "")
)

```

